### ISSUE TITLE
Create menucontent-box to menuscreen

### ISSUE THREAD

**Issue by eminamuratspahic** [liinnjohansson/todays-lunch#18]
Read address info from data.ts
Fixed box.

**Look how menu-content box will interact to menu-content box**

![Skärmavbild 2021-09-23 kl  11 38 44](https://user-images.githubusercontent.com/55393321/134485824-bef99ba2-a41d-41ed-aaac-aeef894f58d3.png)

**Comment by EmelieBrobergs** [comment]
I think It would be nice if the components are clickable. Ex phone number should lead to the phones phone function.. And the mapIcon / address would be nice if they lead to the map in the app ?

**Comment by liinnjohansson** [comment]
Yes, that would be great! I'll have a look at it!
