### ISSUE TITLE
Create navigation code

### ISSUE THREAD

**Issue by eminamuratspahic** [liinnjohansson/todays-lunch#5]
Refactor navigation code from start file. Make it more readable.

* Toggle between BistroScreen.tsx and MapScreen.tsx  - SOLVED in prv. issue
* Refactor the interface placement of mention screen above
* Create navigation to Menu, that can be used within screen by sending id

![Skärmavbild 2021-09-23 kl  10 25 31](https://user-images.githubusercontent.com/55393321/134478639-ec375000-b885-452d-bd60-d314010acd1e.png)
![image](https://user-images.githubusercontent.com/70944598/134485763-cde5df68-7c1e-4184-b2ab-349b317010e9.png)

**Comment by EmelieBrobergs** [comment]
close
