### ISSUE TITLE
Create like-button to bistro-card

### ISSUE THREAD

**Issue by eminamuratspahic** [liinnjohansson/todays-lunch#9]
**Heart code should be able to be implemented on another screen in later issue**

Only creating heart component in this issue. Functionality for toggle etc. will be a another issue.

https://callstack.github.io/react-native-paper/icons.html

![Skärmavbild 2021-09-23 kl  11 02 42](https://user-images.githubusercontent.com/55393321/134480734-81b7ef37-8a43-492e-8d26-e9564892abe1.png)

**Comment by liinnjohansson** [comment]
Used https://callstack.github.io/react-native-paper/icon-button.html instead of suggested component from React Native Paper.
